/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "monitorsScaner_constants.h"

namespace monitorsScaner {

const monitorsScanerConstants g_monitorsScaner_constants;

monitorsScanerConstants::monitorsScanerConstants() {
}

} // namespace

