/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef monitorsScaner_CONSTANTS_H
#define monitorsScaner_CONSTANTS_H

#include "monitorsScaner_types.h"

namespace monitorsScaner {

class monitorsScanerConstants {
 public:
  monitorsScanerConstants();

};

extern const monitorsScanerConstants g_monitorsScaner_constants;

} // namespace

#endif
